### ISSUE TITLE
How to convert UpdateR to scala Future?

### ISSUE THREAD

**Issue by wpoosanguansit** [hazelcast/hazelcast-scala#21]
Hi,

I am following the example I found in the document:

val gaugeValue: Future[Double] = doubles.upsertAndGet("gauge", delta)

This does not compile for me as upsertAndGet returns UpdateR which is the inner type alias to T.  How do we convert that to scala Future?  Thanks for your help.

**Comment by nilskp** [comment]
Not sure if you saw my response on Gitter, but the example from the blog post is missing the `.async` extension.
Also, the `upsertAndGet` signature is `def upsertAndGet(key: K, insertIfMissing: V, runOn: IExecutorService = null)(updateIfPresent: V => V): Future[V]`, so it would look like this:

```scala
val gaugeValue: Future[Double] = doubles.async.upsertAndGet("gauge", initialValue)(_ + delta)
```

**Comment by wpoosanguansit** [comment]
Thank you.  I didn't see your answer in gutter before this.
