### ISSUE TITLE
Hazelcast 4 support?

### ISSUE THREAD

**Issue by Yomanz** [hazelcast/hazelcast-scala#34]
Is this going to support Hazelcast 4??

**Comment by nilskp** [comment]
Probably. I haven't looked into it yet, so I don't know the level of effort required.

Have you tried it on 4? What's the general migration effort?

**Comment by Yomanz** [comment]
> 
> 
> Probably. I haven't looked into it yet, so I don't know the level of effort required.
> 
> Have you tried it on 4? What's the general migration effort?

I can try it on 4 with the app I'm working on if you want.

IDK how much effort it'll take to migrate properly though (the lib).

**Comment by nilskp** [comment]
If the API is mostly backwards compatible, which it sounds like, then it might already work.

**Comment by nilskp** [comment]
It looks like there may be enough breaking changes that it is unlikely to work as-is. However, I don't see the migration being particularly difficult.

**Comment by Yomanz** [comment]
Alright, I'll keep an eye on this repo for the migration :)

**Comment by catalinmer** [comment]
I'll also be interested in Hazelcast 4 support
